"""add tanggal column to waktu_makan

Revision ID: dab9c3b2f944
Revises: 0e9ae34b2942
Create Date: 2025-08-28 03:08:38.737102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dab9c3b2f944'
down_revision = '0e9ae34b2942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waktu_makan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waktu_makan', schema=None) as batch_op:
        batch_op.drop_column('tanggal')

    # ### end Alembic commands ###
